### ISSUE TITLE
Error problem with maven, but report generated

### ISSUE THREAD

**Issue by cyrduf** [cobertura/cobertura#130] opened 2014-01-28 15:16 UTC
Con you give me solution to delete the 2 errors logged in my cobertura use...
I don't find forums dealing with a workaround...
The code coverer is correct with report generation but my goal is to have execution log without error. 

$ mvn clean cobertura:cobertura
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building subproject0 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ subproject0 ---
[INFO] Deleting C:\Eclipse\K2\W\subproject0\target
[INFO]
[INFO] >>> cobertura-maven-plugin:2.6:cobertura (default-cli) @ subproject0 >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ subproject0 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Eclipse\K2\W\subproject0\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ subproject0 ---
[INFO] Compiling 1 source file to C:\Eclipse\K2\W\subproject0\target\classes
[INFO]
[INFO] --- cobertura-maven-plugin:2.6:instrument (default-cli) @ subproject0 ---
[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file

[ERROR] janv. 28, 2014 4:08:28 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler saveCoverageData
Infos: Cobertura: Saved information on 1 classes.

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ subproject0 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Eclipse\K2\W\subproject0\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ subproject0 ---
[INFO] Compiling 4 source files to C:\Eclipse\K2\W\subproject0\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ subproject0 ---
[INFO] Surefire report directory: C:\Eclipse\K2\W\subproject0\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running project.AppAUTOTest
Hello World!
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.085 sec
Running project.AppTest
Hello World!
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running project.AppUTest
Hello World!
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 19, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] <<< cobertura-maven-plugin:2.6:cobertura (default-cli) @ subproject0 <<<
[INFO]
[INFO] --- cobertura-maven-plugin:2.6:cobertura (default-cli) @ subproject0 ---
[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Report time: 157ms

[ERROR] janv. 28, 2014 4:08:31 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
Infos: Cobertura: Loaded information on 1 classes.

[INFO] Cobertura Report generation was successful.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.216s
[INFO] Finished at: Tue Jan 28 16:08:31 CET 2014
[INFO] Final Memory: 21M/225M
[INFO] ------------------------------------------------------------------------

**Comment by dennisl** [comment] 2015-02-27 13:14
Duplicate of #187

**Closed by dennisl** 2015-02-27 13:14 UTC
Labels: duplicate
