### ISSUE TITLE
Error: Could not find or load main class net.sourceforge.cobertura.check.Main

### ISSUE THREAD

**Issue by scmgalaxy** [cobertura/cobertura#118] opened 2014-01-07 09:35 UTC
C:\Users\rkumar11>cd C:\cobertura

C:\cobertura>cobertura-check.bat
Error: Could not find or load main class net.sourceforge.cobertura.check.Main

C:\cobertura>cobertura-check.bat
Error: Could not find or load main class net.sourceforge.cobertura.check.Main

C:\cobertura>ls -1
11.txt                       
cobertura-2.0.3.jar       
cobertura-report.sh
EnhancedFor.java             
cobertura-check.bat       
coberturaFlush.war
LICENSE.txt                  
cobertura-check.sh        
datafile
PrimitiveParameters.java     
cobertura-instrument.bat  
examples
README. markdown              
cobertura-instrument. sh   
instrumented
basedir                      
cobertura-merge.bat       
lib
cobertura-2.0.3-javadoc.jar  
cobertura-merge.sh
cobertura-2.0.3-sources.jar  
cobertura-report.bat

C:\cobertura>echo %JAVA_HOME%
C:\Tools\Java\jdk1.7.0_25
C:\cobertura>echo %JAVA_HOME%
C:\Tools\Java\jdk1.7.0_25

**Comment by dennisl** [comment] 2015-02-27 13:32
Duplicate of Issue #187

**Closed by dennisl** 2015-02-27 13:32 UTC
Labels: duplicate
