### ISSUE TITLE
ParseException Encountered " ")" ") ""

### ISSUE THREAD

**Issue by GerardPaligot** [cobertura/cobertura#219] opened 2015-01-13 10:04 UTC
Hi all,

I would like to add coveralls on the java open source project, [Spoon](https://github.com/INRIA/spoon). I added coveralls and cobertura plugins in the pom.xml of the project but when I execute cobertura plugin, I get a `ParseException`:

```console
[cobertura] WARN  [main] net.sourceforge.cobertura.reporting.ComplexityCalculator - JavaNCSS got an error while parsing the java file /Users/gerard/Documents/workspace/spoon/src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
ParseException in STDIN
Last useful checkpoint: "spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass()"
Encountered " ")" ") "" at line 111, column 49.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...
    "false" ...
    "float" ...
    "int" ...
    "long" ...
    "new" ...
    "null" ...
    "short" ...
    "super" ...
    "this" ...
    "true" ...
    "void" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    <STRING_LITERAL> ...
    <IDENTIFIER> ...
    "(" ...
    "!" ...
    "~" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
```

The line 111 in `CtTypeReferenceImpl.getActualClass()` correspond at  `return (Class<T>) boolean.class;`in the code below.

```java
@SuppressWarnings("unchecked")
public Class<T> getActualClass() {
	if (isPrimitive()) {
		String simpleN = getSimpleName();
		if (simpleN.equals("boolean")) {
			return (Class<T>) boolean.class;
		} else if (simpleN.equals("byte")) {
			return (Class<T>) byte.class;
		} else if (simpleN.equals("double")) {
			return (Class<T>) double.class;
		} else if (simpleN.equals("int")) {
			return (Class<T>) int.class;
		} else if (simpleN.equals("short")) {
			return (Class<T>) short.class;
		} else if (simpleN.equals("char")) {
			return (Class<T>) char.class;
		} else if (simpleN.equals("long")) {
			return (Class<T>) long.class;
		} else if (simpleN.equals("float")) {
			return (Class<T>) float.class;
		} else if (simpleN.equals("void")) {
			return (Class<T>) void.class;
		}
	}
	return findClass();
}
```

Is this a bug or I made something wrong?

Thanks in advance for your help!

**Comment by timchen0** [comment] 2015-02-27 07:22
use jdk1.7_75 cobertura2.1.0-SNAPSHOT
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ">" "> "" at line 128, column 54.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...

**Comment by dennisl** [comment] 2015-02-27 12:31
Duplicate of issue #220

**Closed by dennisl** 2015-02-27 12:31 UTC
Labels: duplicate
