### ISSUE TITLE
NullPointerException during Instrumentation

### ISSUE THREAD

**Issue by jeremylong** [cobertura/cobertura#217] opened 2014-12-27 12:34 UTC
First - thanks for everyones' work on cobertura. However, I've been running into some NPEs during the build of [OWASP dependency-check](https://github.com/jeremylong/DependencyCheck). 

Version Info
--------
cobertura-maven-plugin:2.6

mvn -version
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 08:51:28-0500)
Maven home: c:\java\apache-maven-3.0.5
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: c:\Program Files\Java\jdk1.7.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

Exception Info
-------
```java
[INFO] --- cobertura-maven-plugin:2.6:instrument (report:cobertura) @ dependency-check-core ---
[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[cobertura] WARN  [main] net.sourceforge.cobertura.instrument.CoberturaInstrumenter - Unable to instrument file C:\Users
\jeremy\Documents\NetBeansProjects\DependencyCheck\dependency-check-core\target\generated-classes\cobertura\org\owasp\dependencycheck\data\nvdcve\CveDB.class
java.lang.NullPointerException
        at java.util.LinkedList.addAll(LinkedList.java:406)
        at java.util.LinkedList.addAll(LinkedList.java:385)
        at java.util.LinkedList.<init>(LinkedList.java:117)
        at net.sourceforge.cobertura.instrument.FindTouchPointsMethodAdapter.visitLineNumber(FindTouchPointsMethodAdapter.java:196)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
        at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
        at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)
[cobertura] WARN  [main] net.sourceforge.cobertura.instrument.CoberturaInstrumenter - Unable to instrument file C:\Users\jeremy\Documents\NetBeansProjects\DependencyCheck\dependency-check-core\target\generated-classes\cobertura\org\owasp\dependencycheck\data\update\task\DownloadTask.class
java.lang.NullPointerException
        at java.util.LinkedList.addAll(LinkedList.java:406)
        at java.util.LinkedList.addAll(LinkedList.java:385)
        at java.util.LinkedList.<init>(LinkedList.java:117)
        at net.sourceforge.cobertura.instrument.FindTouchPointsMethodAdapter.visitLineNumber(FindTouchPointsMethodAdapter.java:196)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
        at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
        at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
        at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
        at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)

[ERROR] Dec 27, 2014 7:08:51 AM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler saveCoverageData
INFO: Cobertura: Saved information on 200 classes.
```

**Comment by col6y** [comment] 2015-02-03 01:55
I'm running into the same issue with an unrelated codebase:

	[cobertura-instrument] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
	[cobertura-instrument] WARN   instrumentClass, Unable to instrument file C:\Users\skeggsc\Documents\CCRE2015\CommonChickenRuntimeEngine\bin\ccre\cluck\tcp\CluckTCPClient.class
	[cobertura-instrument] java.lang.NullPointerException
	[cobertura-instrument] 	at java.util.LinkedList.addAll(LinkedList.java:406)
	[cobertura-instrument] 	at java.util.LinkedList.addAll(LinkedList.java:385)
	[cobertura-instrument] 	at java.util.LinkedList.<init>(LinkedList.java:117)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.FindTouchPointsMethodAdapter.visitLineNumber(FindTouchPointsMethodAdapter.java:196)
	[cobertura-instrument] 	at org.objectweb.asm.ClassReader.a(Unknown Source)
	[cobertura-instrument] 	at org.objectweb.asm.ClassReader.b(Unknown Source)
	[cobertura-instrument] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	[cobertura-instrument] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:161)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
	[cobertura-instrument] 	at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)
	[cobertura-instrument] Feb 02, 2015 5:48:06 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler saveCoverageData
	[cobertura-instrument] INFO: Cobertura: Saved information on 292 classes.

I'm using the `cobertura-instrument` ant task under Oracle Java 1.7.0_40 on code compiled to target Java 1.5. Java home is `C:\Program Files\Java\jdk_1.7.0_40`, on 64-bit Windows 7.

**Comment by col6y** [comment] 2015-02-03 01:58
It should be noted that this only seems to happen (for me) with the `ignoretrivial` option enabled.

**Comment by col6y** [comment] 2015-02-03 23:35
Self-contained demonstration of this issue:

    public class SelfContained {
        private int number = 6;
    
        public int getNumber() {
            return number;
        }
    
        public void setNumber(int number) {
            this.number = number;
        }
    
        public void nothing() {
        }
    
        public void tryConnection() {
            try {
                throw new IOException();
            } catch (IOException ex) {
                if (number != 0) {
                    return;
                } else {
                    nothing();
                }
            } finally {
                number = 0;
                number = 0;
            }
        }
    }

It seems like a really complicated self-contained demonstration, but somehow without that it won't cause the issue. (For example, changing the `6` to a `5` fixes it. Or removing one of the `number = 0;` lines or removing one of the "trivial" methods.)

**Comment by dennisl** [comment] 2015-02-27 12:35
Duplicate of issue #200

**Closed by dennisl** 2015-02-27 12:35 UTC
Labels: duplicate
