### ISSUE TITLE
NullPointerException 	in TouchCollector after upgrade to 2.1.1

### ISSUE THREAD

**Issue by jakub-bochenski** [cobertura/cobertura#250] opened 2015-05-27 16:00 UTC
This happens when trying to start Tomcat webapp with some instrumented classes placed in a jar in `WEB-INF/lib`. The .jar was produced with cobertura-maven-plugin:instrument goal (v. 2.7)

When I swap `cobertura-2.1.1.jar` for `cobertura-2.1.0-SNAPSHOT.jar` (Thu Aug 28 19:19:38 PDT 2014) everything works fine.

Running unit tests etc. works fine regardless of version.

Full stack trace (the class is a custom Log4J appender):

```
java.lang.ExceptionInInitializerError
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:247)
    at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
    at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
    at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
    at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
    at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1001)
    at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:867)
    at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:773)
    at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
    at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
    at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:73)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:242)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:254)
    at net.sourceforge.cobertura.coveragedata.TouchCollector.<clinit>(TouchCollector.java:40)
[ .. SNIP .. ]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:134)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at net.sourceforge.cobertura.coveragedata.TouchCollector.registerClass(TouchCollector.java:49)
    at net.sourceforge.cobertura.coveragedata.TouchCollector.registerClass(TouchCollector.java:85)
```

Possible duplicate of #230, but the reporter didn't provide enough details.
Java 1.7.0_60-b19, 64 bit; Ubuntu 12.04  LTS

**Comment by bcoughlan** [comment] 2015-06-25 16:12
FWIW I get the same error using a custom Log4j appender. 

I get this warning also when running "mvn site" (with the cobertura plugin).

log4j:WARN No appenders could be found for logger (net.sourceforge.cobertura.coveragedata.TouchCollector).

Will be investigating this further in a couple of weeks.

**Comment by bcoughlan** [comment] 2015-08-05 14:57
I can confirm that the problem occurs because of the custom appender. Taking it out fixes the problem. Even having an empty class as a custom appender causes the same issue. Could it be related to the way that Cobertura loads classes? Note that the custom appender is in the same project so the class file has been instrumented too.

**Comment by Dru89** [comment] 2015-10-08 22:28
I was also able to reproduce this problem happening with a custom appender.  Removing it seems to make everything work again.  Any known fixes for it, yet?

**Comment by bcoughlan** [comment] 2015-10-13 23:37
I gave up in it in the end because I don't know much about cobertura internals. An idea could be to use different maven profiles to override the log4j file just for the code coverage part of a build

**Comment by rvangsgaard** [comment] 2016-06-28 09:28
I experience the same with a custom PatternLayout.

**Closed** 2017-11-19 03:30 UTC
