### ISSUE TITLE
cobertura-maven-plugin fails to run on FreeBSD

### ISSUE THREAD

**Issue by TinnedTuna** [cobertura/cobertura#221] opened 2015-01-20 10:10 UTC
On FreeBSD, 10.0-RELEASE-p12, the Maven plugin fails to run, bailing with a  NoClassDefFoundError.

### Machine Details

    % mvn -version
    Apache Maven 2.2.1 (r801777; 2009-08-06 20:16:01+0100)
    Java version: 1.7.0_71
    Java home: /usr/local/openjdk7/jre
    Default locale: en_GB, platform encoding: UTF-8
    OS name: "freebsd" version: "10.0-release-p12" arch: "amd64" Family: "unix"

    % uname -a
    FreeBSD aew6pc07 10.0-RELEASE-p12 FreeBSD 10.0-RELEASE-p12 #0: Tue Nov 4 05:07:17 UTC 2014
    root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

### Reproduction Steps

  1. Move ~/.m2 directory somewhere safe (e.g. ~/.m2-backup)
  2. mvn archetype:generate, generate a default project, arbitrary groupId & artifactId.
  3. Enter the new project directory and issue mvn cobertura:cobertura

### Expected Results

Maven downloads all of Cobertura's dependencies, instruments the code, successfully runs the example JUnit test (AppTest.java) and produces a HTML report.

### Actual Results

The mvn cobertura:cobertura plugin bails with a stack trace, somewhere in the instrumentation goal. The stack trace has, for example:

    java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at net.sourceforge.cobertura.util.CommandLineBuilder.<clinit>(CommandLineBuilder.java:72) 

(Thanks to Robert Scholte for pointing out that line of log)

### Relevant Files

I'm not sure how to attach the logs/example maven project I created to a github issue; so, if you need it, let us know and I'll make sure it reaches you (or get it attached to the issue).

### Other Details

My co-workers' machine runs the cobertura goals fine, their machine specs are:

    $ mvn -version
    Apache Maven 2.2.1 (rdebian-8)
    Java version: 1.7.0_65
    Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
    Default locale: en_GB, platform encoding: UTF-8
    OS name: "linux" version: "3.2.0-4-amd64" arch: "amd64" Family: "unix"

    $ uname -a
    Linux aew6pc09 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u2 x86_64 GNU/Linux

**Comment by dennisl** [comment] 2015-01-20 11:45
If you experience the same behavior when you run Cobertura from the command line (i.e. not using Maven) the issue belongs here. However if it works from the command line but not using the Maven plugin, the issue should be files at https://jira.codehaus.org/browse/MCOBERTURA

Cobertura and the Maven plugin for it are different projects with different issue trackers.

**Comment by TinnedTuna** [comment] 2015-01-20 12:07
Hi Dennisl,

I originally filed this bug report via email directly to the cobertura-maven-plugin team, who triaged the issue as being a cobertura issue and sent me here :-/

I don't usually run cobertura directly from the command line, only via the maven plugin; how would I go about getting at cobertura to run it directly?

**Comment by blakeney** [comment] 2015-02-04 00:00
This issue looks like a duplicate of #121, which was fixed with Pull Request #126.  That enhancement came after the 2.0.3 release of Cobertura, however, and that's the version that the Maven plugin uses.  Version 2.0.3 appears to be from August 2013, and as far as I can tell it's the latest stable release.  Is that correct?  Are the any plans for a new release in the near future?

**Comment by dennisl** [comment] 2015-03-03 08:12
Cobertura 2.1.1 and Cobertura Maven Plugin 2.7 has just been released. Please try them, to see is they solve your issue.

**Comment by TinnedTuna** [comment] 2015-03-03 10:35
This does fix the issue! Thank you very much for your time.

However, I did have to move my ~/.m2 directory to a backup location. It seems that it had become some-how "tainted" by the bug.

**Comment by dennisl** [comment] 2015-03-03 12:19
Thanks for reporting back.

**Closed by dennisl** 2015-03-03 12:19 UTC

**Comment by blakeney** [comment] 2015-03-04 02:44
Thank you for rolling out the new release with this fix included!  By the way, if anyone would like to clear the old Cobertura and its Maven plugin from a local repository without having to wipe the whole thing, this did the job for me:

```
rm -rf ~/.m2/repository/org/codehaus/mojo/cobertura-maven-plugin ~/.m2/repository/net/sourceforge/cobertura/cobertura
```
