### ISSUE TITLE
[Error] net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " "(" "( ""

### ISSUE THREAD

**Issue by M3hrL1cht** [cobertura/cobertura#242] opened 2015-04-01 10:20 UTC
I'm troubled by a ParseException caused by a bracket in my code. 
Console:
```
[WARN] JavaNCSS got an error while parsing the java file S:\Projekte\onedata-server\Common\DataTypes\src\main\java\de\onelogic\forecasting\exchange\dataset\Attribute.java
ParseException in STDIN
Last useful checkpoint: "de.onelogic.forecasting.exchange.dataset.Attribute"
Encountered " "(" "( "" at line 51, column 14.
Was expecting one of:
    "assert" ...
    "enum" ...
    <IDENTIFIER> ...
    <IDENTIFIER> ...
    "assert" ...
    "assert" ...
    "assert" ...
    "assert" ...
    "assert" ...
    "assert" ...
    "assert" ...
    "assert" ...
    "assert" ...
    "assert" ...
    

```

Code (bracket in question is "ViewsRef (@JsonProperty"):
```
  @JsonCreator
    public @Valid ViewsRef (@JsonProperty("id") UUID id, @JsonProperty("uri") String uri, @JsonProperty("name") String name,
            @JsonProperty("tags") String[] tags, @JsonProperty("description") String description) {
```

**Comment by dennisl** [comment] 2015-04-01 11:14
This is a duplicate of #176

**Closed by dennisl** 2015-04-01 11:14 UTC
Labels: duplicate
