### ISSUE TITLE
Error parsing Java 7 binary literals

### ISSUE THREAD

**Issue by shevek** [cobertura/cobertura#223] opened 2015-01-29 21:41 UTC
```
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " <IDENTIFIER> "b11 "" at line 71, column 37.
Was expecting one of:
    "instanceof" ...
    ")" ...
    "," ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    "+=" ...
    "-=" ...
    "*=" ...
    "/=" ...
    "&=" ...
    "|=" ...
    "^=" ...
    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:11869)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:11730)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3539)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.AllocationExpression(JavaParser.java:3587)
```

See https://github.com/stevesaliman/gradle-cobertura-plugin/issues/69

**Comment by shevek** [comment] 2015-01-30 04:31
Test case: https://github.com/shevek/ipmi4j

**Comment by dalvizu** [comment] 2015-02-06 05:32
I've put in a test case, so it can at least be instrumented and reported on in 2.1.0-SNAPSHOT. 

Where are you seeing this error? What version of the cobertura are you using? Can you include more in the stack trace? this package - net.sourceforge.cobertura.javancss.parser - comes from the javacc-maven-plugin  and I can't find any known issues with binary literals in javacc.

**Comment by 125m125** [comment] 2015-02-06 13:35
I am experiencing the same issue.

my full stacktrace after running `mvn clean cobertura:cobertura` :

    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building nineMensMorrisv2 0.0.1-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nineMensMorrisv2 ---
    [INFO] Deleting [...]/nineMensMorrisv2/target
    [INFO] 
    [INFO] >>> cobertura-maven-plugin:2.6:cobertura (default-cli) @ nineMensMorrisv2 >>>
    [INFO] 
    [INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ nineMensMorrisv2 ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 0 resource
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ nineMensMorrisv2 ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 34 source files to [...]/nineMensMorrisv2/target/classes
    [INFO] 
    [INFO] --- cobertura-maven-plugin:2.6:instrument (default-cli) @ nineMensMorrisv2 ---
    [INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file

    [ERROR] Feb 06, 2015 2:09:44 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler saveCoverageData
    INFO: Cobertura: Saved information on 36 classes.

    [INFO] Instrumentation was successful.
    [INFO] NOT adding cobertura ser file to attached artifacts list.
    [INFO] 
    [INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ nineMensMorrisv2 ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 1 resource
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ nineMensMorrisv2 ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 20 source files to [...]/nineMensMorrisv2/target/test-classes
    [INFO] 
    [INFO] --- maven-surefire-plugin:2.10:test (default-test) @ nineMensMorrisv2 ---
    [INFO] Surefire report directory: [...]/nineMensMorrisv2/target/surefire-reports

    -------------------------------------------------------
     tests
    -------------------------------------------------------
    [...]

    Results :

    Tests run: 107, Failures: 0, Errors: 0, Skipped: 0

    [INFO] 
    [INFO] <<< cobertura-maven-plugin:2.6:cobertura (default-cli) @ nineMensMorrisv2 <<<
    [INFO] 
    [INFO] --- cobertura-maven-plugin:2.6:cobertura (default-cli) @ nineMensMorrisv2 ---
    [INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
    [cobertura] WARN  [main] net.sourceforge.cobertura.reporting.ComplexityCalculator - JavaNCSS got an error while parsing the java file [...]/nineMensMorrisv2/src/main/java/com/ecosim125/nineMensMorrisv2/board/PlayBoard.java
    ParseException in STDIN
    Last useful checkpoint: "com.ecosim125.nineMensMorrisv2.board.PlayBoard"
    Encountered " <IDENTIFIER> "b1000 "" at line 27, column 53.
    Was expecting one of:
    "instanceof" ...
    ";" ...
    "," ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    "+=" ...
    "-=" ...
    "*=" ...
    "/=" ...
    "&=" ...
    "|=" ...
    "^=" ...
    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...
    

    [cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/ecosim125/nineMensMorrisv2/display/Display.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
    [cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/ecosim125/nineMensMorrisv2/event/manager/Cancelable.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
    [cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/ecosim125/nineMensMorrisv2/event/manager/EventHandler.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
    [cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/ecosim125/nineMensMorrisv2/event/manager/Listener.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
    [cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file com/ecosim125/nineMensMorrisv2/event/manager/SingleServable.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
    Report time: 2547ms

    [ERROR] Feb 06, 2015 2:10:20 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
    INFO: Cobertura: Loaded information on 36 classes.
    net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " <IDENTIFIER> "b1000 "" at line 27, column 53.
    Was expecting one of:
    "instanceof" ...
    ";" ...
    "," ...
    "=" ...
    ">" ...
    "<" ...
    "?" ...
    "==" ...
    "<=" ...
    ">=" ...
    "!=" ...
    "||" ...
    "&&" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "&" ...
    "|" ...
    "^" ...
    "%" ...
    "+=" ...
    "-=" ...
    "*=" ...
    "/=" ...
    "&=" ...
    "|=" ...
    "^=" ...
    "%=" ...
    "<<=" ...
    ">>=" ...
    ">>>=" ...
    ">" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:11869)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:11730)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.FieldDeclaration(JavaParser.java:1616)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1043)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:874)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:801)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:706)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:555)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:303)
	at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)
	at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:192)
	at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:268)
	at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:346)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSource(ComplexityCalculator.java:105)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:234)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:201)
	at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:167)
	at net.sourceforge.cobertura.reporting.html.HTMLReport.generateTableRowForTotal(HTMLReport.java:603)
	at net.sourceforge.cobertura.reporting.html.HTMLReport.generateOverview(HTMLReport.java:287)
	at net.sourceforge.cobertura.reporting.html.HTMLReport.generateOverviews(HTMLReport.java:228)
	at net.sourceforge.cobertura.reporting.html.HTMLReport.<init>(HTMLReport.java:71)
	at net.sourceforge.cobertura.reporting.Main.parseArguments(Main.java:103)
	at net.sourceforge.cobertura.reporting.Main.main(Main.java:169)

    [INFO] Cobertura Report generation was successful.
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1:06.034s
    [INFO] Finished at: Fri Feb 06 14:10:22 CET 2015
    [INFO] Final Memory: 20M/107M
    [INFO] ------------------------------------------------------------------------

Line 27 of PlayBoard.java looks like this:
`     private static final short             JUMP  = 0b1000;`

**Comment by shevek** [comment] 2015-02-08 04:56
@dalvizu If you check out the test case repo I posted and run "./gradlew clean build coberturaReport" it will reproduce. If you run "./gradlew dependencies" it will show the various versions of cobertura etc it's using.

**Comment by shevek** [comment] 2015-02-08 04:57
```
        at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:11869)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.jj_consume_token(JavaParser.java:11730)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3539)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.AllocationExpression(JavaParser.java:3587)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimaryPrefix(JavaParser.java:3379)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.PrimaryExpression(JavaParser.java:3300)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.PostfixExpression(JavaParser.java:3254)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpressionNotPlusMinus(JavaParser.java:3162)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.UnaryExpression(JavaParser.java:3096)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.MultiplicativeExpression(JavaParser.java:3016)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.AdditiveExpression(JavaParser.java:2988)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ShiftExpression(JavaParser.java:2955)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.RelationalExpression(JavaParser.java:2919)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.InstanceOfExpression(JavaParser.java:2906)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.AssigmentExpression(JavaParser.java:2889)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.EqualityExpression(JavaParser.java:2817)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.AndExpression(JavaParser.java:2792)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ExclusiveOrExpression(JavaParser.java:2776)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.InclusiveOrExpression(JavaParser.java:2760)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalAndExpression(JavaParser.java:2743)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalOrExpression(JavaParser.java:2726)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ConditionalExpression(JavaParser.java:2710)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.Expression(JavaParser.java:2654)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ArgumentList(JavaParser.java:3543)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.Arguments(JavaParser.java:3533)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.EnumConstant(JavaParser.java:5593)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.EnumBody(JavaParser.java:5382)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.EnumDeclaration(JavaParser.java:5209)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBodyDeclaration(JavaParser.java:1008)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassBody(JavaParser.java:874)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.UnmodifiedClassDeclaration(JavaParser.java:801)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.ClassDeclaration(JavaParser.java:706)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.TypeDeclaration(JavaParser.java:555)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.CompilationUnit(JavaParser.java:303)
        at net.sourceforge.cobertura.javancss.parser.JavaParser.parse(JavaParser.java:100)
        at net.sourceforge.cobertura.javancss.Javancss._measureSource(Javancss.java:192)
        at net.sourceforge.cobertura.javancss.Javancss._measureRoot(Javancss.java:268)
        at net.sourceforge.cobertura.javancss.Javancss.<init>(Javancss.java:346)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSource(ComplexityCalculator.java:105)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getAccumlatedCCNForSingleFile(ComplexityCalculator.java:143)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForSourceFileNameInternal(ComplexityCalculator.java:234)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForPackageInternal(ComplexityCalculator.java:201)
        at net.sourceforge.cobertura.reporting.ComplexityCalculator.getCCNForProject(ComplexityCalculator.java:167)
        at net.sourceforge.cobertura.reporting.xml.XMLReport.<init>(XMLReport.java:67)
        at net.sourceforge.cobertura.reporting.Main.parseArguments(Main.java:106)
        at net.sourceforge.cobertura.reporting.Main.main(Main.java:169)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at net.saliman.gradle.plugin.cobertura.CoberturaRunner.executeCobertura(CoberturaRunner.groovy:224)
        at net.saliman.gradle.plugin.cobertura.CoberturaRunner.this$2$executeCobertura(CoberturaRunner.groovy)
        at net.saliman.gradle.plugin.cobertura.CoberturaRunner$this$2$executeCobertura$2.callCurrent(Unknown Source)
        at net.saliman.gradle.plugin.cobertura.CoberturaRunner.generateCoverageReport(CoberturaRunner.groovy:116)
        at net.saliman.gradle.plugin.cobertura.CoberturaRunner$generateCoverageReport$3.call(Unknown Source)
        at net.saliman.gradle.plugin.cobertura.GenerateReportTask.generateReports(GenerateReportTask.groovy:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by raniejade** [comment] 2015-02-16 00:29
Duplicate of #220, it's an issue with the bundled JavaNCSS.

**Closed** 2015-02-27 12:25 UTC
Labels: duplicate

**Comment by knitterb-razzle** [comment] 2015-03-26 23:24
With version 2.7 I get the same binary parse error on something like this:

	public enum MyEnum {
		a(0b1), b(0b10), c(0b100);

		private int bitMask;

		private MyEnum(int bitMask) {
			this.bitMask = bitMask;
		}
        }


Hope this helps!
