### ISSUE TITLE
cobertura-instrument.sh from cobertura binary files references missing jar files

### ISSUE THREAD

**Issue by flgr** [cobertura/cobertura#83] opened 2013-10-01 13:58 UTC
This has been the case for every release since 2.0.0.

cobertura-instrument.sh references the files lib/asm-3.3.1.jar, lib/asm-tree-3.3.1.jar etc., which don't exist.

Instead cobertura ships with asm-4.1.jar, asm-tree-4.1.jar and so on. Changing the references in the script to she shipped libraries will lead to compatibility errors:

Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/util/CheckClassAdapter

So it looks like Cobertura needs an older version of ASM (3.3.1) when it in fact ships with one too new for it to actually work with.

**Comment by dennisl** [comment] 2015-03-03 07:50
Duplicate of #137

**Closed by dennisl** 2015-03-03 07:50 UTC
Labels: duplicate
